### ISSUE TITLE
User can view the soccer clubs #1

### ISSUE THREAD

**Issue by adesai47** [adesai47/front-end-project#2]
## ⚙️ Feature

User can view the soccer clubs

## 📐 Functionality

User will be able to see different soccer clubs and click on them to see the starting 11 players and the amount of trophies that the club has acquired.

## 🖼️ Wireframes

<img width="142" alt="Screenshot 2024-06-20 at 2 04 02 PM" src="https://github.com/adesai47/front-end-project/assets/87247195/12233f53-57d9-4350-86db-5ddf69dc2f74">

<img width="461" alt="Screenshot 2024-06-20 at 2 04 18 PM" src="https://github.com/adesai47/front-end-project/assets/87247195/13b72484-b62e-4090-96a0-d84bca44c9e9">

## ✅ Task List

- [ ] Create a header with the app title "FootRanking".
- [ ] Add navigation tabs for "Teams" and "Favorites".
- [ ] Add images for the soccer clubs
- [ ] Display a grid layout of soccer club logos with their names underneath.
- [ ] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [ ] Set up click events for navigation tabs to switch between "Teams" and "Favorites".
- [ ] Ensure smooth transitions between different views.
- [ ] Use an API or a predefined data source to fetch club data including name, logo, trophies, and starting XI.
- [ ] Display the fetched data in the grid layout.
- [ ] Use colors, fonts, and spacing to create a visually appealing and user-friendly interface.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
