### ISSUE TITLE
User can see the starting 11 players when selecting a soccer club #2

### ISSUE THREAD

**Issue by adesai47** [adesai47/front-end-project#4]
## ⚙️ Feature

User can see the starting 11 players when selecting the soccer club of their choice

## 📐 Functionality

It will allow the user to be able to see out of the six teams shown, the starting 11 players of each of the teams

## 🖼️ Wireframes

<img width="142" alt="Screenshot 2024-06-20 at 2 04 02 PM" src="https://github.com/adesai47/front-end-project/assets/87247195/db071093-dc01-4309-9a0f-5e5968dad6b5">
<img width="461" alt="Screenshot 2024-06-20 at 2 04 18 PM" src="https://github.com/adesai47/front-end-project/assets/87247195/843ca583-f67b-4836-908d-a2c639c29931">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [ ] Identify the API endpoint to fetch the starting 11 players for a selected team.
- [ ] Update the data.ts file to include a function for fetching starting 11 players
- [ ] Ensure there is a section to display the starting 11 players when a team is selected.
- [ ] Modify the details-view section to include a container for the starting 11 players.
- [ ] Update main.ts to fetch the starting 11 players when a team is selected.
- [ ] Update the data.ts file to include a function for fetching starting 11 players
- [ ] Render the starting 11 players in the details-view section.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
