### ISSUE TITLE
Feature: User can favorite and unfavorite team #3

### ISSUE THREAD

**Issue by adesai47** [adesai47/front-end-project#6]
## ⚙️ Feature

User can favorite the club of their choosing.

## 📐 Functionality

User will see a heart that can be used to favorite the team and the favorited team will be sent to the favorites page.

## 🖼️ Wireframes

<img width="142" alt="Screenshot 2024-06-20 at 2 04 02 PM" src="https://github.com/adesai47/front-end-project/assets/87247195/9b6c5116-92dd-4bea-8a7b-5407bd63c2b5">
<img width="461" alt="Screenshot 2024-06-20 at 2 04 18 PM" src="https://github.com/adesai47/front-end-project/assets/87247195/635973d4-5154-4269-8042-139deea580e1">

## ✅ Task List

- [ ] Add a container in the HTML file for the favorites section.
- [ ] Ensure it has an ID of favorites-container and is initially hidden.
- [ ] Add an event listener for the favorites tab to display the favorites view when clicked.
- [ ] Add a button or clickable element to each team card to allow users to favorite a team.
- [ ] Use localStorage to save the favorite teams across sessions.
- [ ] On page load, fetch the favorite teams from localStorage.
- [ ] Display the favorite teams in the favorites section.
- [ ] Add functionality to remove a team from the favorites.
- [ ] Update the localStorage and the favorites section accordingly.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
